port: "8000"

db: 
  username: "postgres"
  password: "postgres"
  host: "127.0.0.1"
  port: "5432"
  dbname: "test"
  sslmode: "disable"

natStreaming:
  clusterId: "test-cluster"
  clientId: "test-client"
  natsURL: "nats://localhost:4222"
